version: "2"
services:
    api:
        image: api
        build: .
        ports:
            - "8000:8000"
        expose:
            - "8000"
        volumes:
            - ./:/app
        restart: always
        environment:
            - ENV_STATE=dev
